name: facebook_reaction_animation
description: Facebook reaction animation with Flutter
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - sounds/

environment:
  sdk: ">=2.12.0 <3.0.0"