name: facebook_reaction_animation
description: Facebook reaction animation with Flutter
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

environment:
  sdk: '>=3.1.5 <4.0.0'
